# Generated by Django 4.1.7 on 2023-05-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_director_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movie_app.director'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_email',
            field=models.EmailField(max_length=254),
        ),
    ]
